# Generated by Django 4.2.6 on 2023-11-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('picture', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
