# Generated by Django 4.2.6 on 2024-01-18 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap', '0003_rename_profile_pic_scraps_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
