# Generated by Django 4.2.6 on 2024-01-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_alter_scraps_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='scrap_pic'),
        ),
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], default='available', max_length=200),
        ),
    ]
