# Generated by Django 4.2.6 on 2024-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_alter_scraps_picture_alter_scraps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=200),
        ),
    ]
