# Generated by Django 4.2.6 on 2024-01-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_alter_scraps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='picture',
            field=models.ImageField(null=True, upload_to='scrap_pic'),
        ),
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], default='available', max_length=200),
        ),
    ]
