# Generated by Django 4.2.6 on 2024-01-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_alter_scraps_picture_alter_scraps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='scrap_pic'),
        ),
    ]
