# Generated by Django 4.2.6 on 2024-01-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_scraps_wishlist_users_alter_scraps_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraps',
            name='wishlist_users',
        ),
    ]
