# Generated by Django 4.2.6 on 2024-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_remove_scraps_wishlist_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], default='available', max_length=200),
        ),
    ]
