# Generated by Django 4.2.6 on 2024-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_rename_picture_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=200),
        ),
    ]
