# Generated by Django 4.2.6 on 2024-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_alter_scraps_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.PositiveIntegerField()),
                ('Bankname', models.CharField(max_length=200)),
                ('IFSC', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('payment', models.CharField(choices=[('UPI', 'UPI'), ('credit/debit card', 'credit/debit card'), ('Rupay', 'Rupay')], default='UPI', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=200),
        ),
    ]
